name: "Render docs"

on:
  push:
    branches:
      - "*"
  pull_request:
    branchess:
      - "*"
             
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with: 
          path: docs/_build/html/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4 
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
